// Generated by Claude Smart Receiver - 2025-06-21 08:29
jQuery(document).ready(function($) {
    var mediaRecorder;
    var audioChunks = [];
    var videoChunks = [];
    var stream;
    var timerInterval;
    var recordingTime = 0;
    var currentCartKey = '';
    var currentProductId = '';
    var currentRecordingKey = '';
    var isAudioRecording = true;

    $(document).on('click', '.wc-record-button', function() {
        currentCartKey = $(this).data('cart-key');
        currentProductId = $(this).data('product-id');
        currentRecordingKey = $(this).data('recording-key');

        $('#wc-current-product-id').val(currentProductId);
        $('#wc-current-cart-key').val(currentCartKey);
        $('#wc-current-recording-key').val(currentRecordingKey);

        $.ajax({
            url: wc_recording_params.ajax_url,
            type: 'POST',
            data: {
                action: 'get_product_recording',
                security: wc_recording_params.recording_nonce,
                cart_key: currentCartKey
            },
            success: function(response) {
                if (response.success && response.data.recording_id) {
                    $('#wc-recording-alert').text('Ten produkt ma już nagranie. Nowe nagranie zastąpi poprzednie.').show();
                } else {
                    $('#wc-recording-alert').text(wc_recording_params.warning_text).show();
                }
            }
        });

        $('#wc-recording-modal').show();
        $('#wc-recording-modal-overlay').show();
    });

    $('.wc-recording-close, #wc-recording-modal-overlay').click(function() {
        stopRecording();
        $('#wc-recording-modal').hide();
        $('#wc-recording-modal-overlay').hide();
        resetRecordingUI();
   Oto kontynuacja skryptu JavaScript (`assets/js/recording.js`), aby zakończyć funkcjonalność nagrywania audio/wideo oraz zamknąć modal:

### Kontynuacja pliku: `assets/js/recording.js`

```javascript
 });

 function startRecording() {
  if (isAudioRecording) {
   navigator.mediaDevices.getUserMedia({ audio: true })
   .then(function(streamParam) {
    stream = streamParam;
    mediaRecorder = new MediaRecorder(stream);
    mediaRecorder.start();
    
    mediaRecorder.ondataavailable = function(event) {
     audioChunks.push(event.data);
    };

    mediaRecorder.onstop = function() {
     const audioBlob = new Blob(audioChunks, { type: 'audio/webm' });
     audioChunks = [];

     const formData = new FormData();
     formData.append('recording', audioBlob, 'recording.webm');
     formData.append('cart_key', currentCartKey);
     formData.append('product_id', currentProductId);

     $.ajax({
      url: wc_recording_params.ajax_url,
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      success: function(response) {
       if (response.success) {
        $('#wc-recording-alert').text('Nagranie zapisano.').show();
        // Optionally handle the recording ID and UI updates here
       }
      }
     });
    };
    
    startTimer();
   });
  } else {
   // Wersja wideo, do implementacji według własnych wskazówek
   navigator.mediaDevices.getUserMedia({ video: true, audio: true })
   .then(function(streamParam) {
    stream = streamParam;
    mediaRecorder = new MediaRecorder(stream);
    mediaRecorder.start();
    
    mediaRecorder.ondataavailable = function(event) {
     videoChunks.push(event.data);
    };
   
    mediaRecorder.onstop = function() {
     const videoBlob = new Blob(videoChunks, { type: 'video/webm' });
     videoChunks = [];

     const formData = new FormData();
     formData.append('recording', videoBlob, 'recording.webm');
     formData.append('cart_key', currentCartKey);
     formData.append('product_id', currentProductId);

     $.ajax({
      url: wc_recording_params.ajax_url,
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      success: function(response) {
       if (response.success) {
        $('#wc-recording-alert').text('Nagranie zapisano.').show();
       }
      }
     });
    };

    startTimer();
   });
  }
 }

 function stopRecording() {
  mediaRecorder.stop();
  stream.getTracks().forEach(track => track.stop());
  clearInterval(timerInterval);
 }

 function startTimer() {
  recordingTime = 0;
  $('#wc-recording-controls').show();

  timerInterval = setInterval(function() {
   recordingTime++;
   var minutes = Math.floor(recordingTime / 60);
   var seconds = recordingTime % 60;
   $('#wc-recording-timer').text((minutes < 10 ? '0' : '') + minutes + ':' + (seconds < 10 ? '0' : '') + seconds);
  }, 1000);
 }

 function resetRecordingUI() {
  recordingTime = 0;
  $('#wc-recording-timer').text('00:00');
  $('#wc-recording-controls').hide();
 }

 $('#wc-start-audio').click(function() {
  isAudioRecording = true;
  startRecording();
 });

 $('#wc-start-video').click(function() {
  isAudioRecording = false;
  startRecording();
 });
});